timesheetmanagement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from workdaymanagement import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.GenerateReport,name='home'),
    path('workday/',include('workdaymanagement.urls',namespace='Workday')),
    path('user/',include('usermanagement.urls',namespace='Users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

usermanagement/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from usermanagement import views

app_name = 'Users'
urlpatterns=[
    re_path('^userslist$',views.UsersList.as_view(),name='userslist'),
    re_path('^new$',views.ProfileCreate.as_view(),name='new'),
    re_path('^(?P<pk>[0-9]+)/update$',views.ProfileUpdate.as_view(),name='profileupdate'),
    re_path('^(?P<pk>[0-9]+)/delete$',views.ProfileDelete.as_view(),name='profiledelete'),
    re_path('^login$',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    re_path('^logout$',auth_views.LogoutView.as_view(template_name='users/logged_out.html'),name='logout'),
    re_path('^signup$',views.signup,name='signup'),
    re_path('^(?P<pk>[0-9]+)$',views.ProfileDetail.as_view(),name='profiledetail'),
]

workdaymanagement/urls.py
from django.urls import path, re_path
from workdaymanagement import views
from workdaymanagement.views import WorkdayDelete,WorkdayUpdate

app_name='Workday'
urlpatterns=[
   re_path('^workdaylist$',views.GetList.as_view(),name='workday_list'),
   re_path('^new$',views.WorkdayCreate.as_view(),name="new_workday"),
   re_path('^(?P<pk>[0-9]+)/update$',views.WorkdayUpdate.as_view(),name="workday_edit"),
   re_path('^(?P<pk>[0-9]+)/delete$',WorkdayDelete.as_view(),name="workday_delete"),
   re_path('^report$',views.GenerateReport),
   re_path('^(?P<pk>[0-9]+)$', views.UserDetail.as_view(), name="workday_detail"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>TimesheetManagement</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Timesheet</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Users:logout' %}">Logout   Hi {{user.username}}</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Users:login' %}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            Doctors
          </a>
          <ul class="dropdown-menu dropdown-menu-light">
            <li><a class="dropdown-item" href="{% url 'Users:userslist' %}">View Doctors</a></li>
            <li>
              <a class="dropdown-item" href="{% url 'Users:new' %}">Add Doctors</a>
            </li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'Workday:workday_list' %}">Workdays</a>
        </li>
      </ul>
      <form class="d-flex" method="GET" action="{% url 'Users:userslist' %}">
         <input class="form-control me-2" name="q" value="{{request.GET.q}}" type="search" placeholder="Search Doctor" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %} {% endblock %}

<script crossorigin="anonymous"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
        integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
        crossorigin="anonymous"></script>


</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid mt-4">
<h1>Welcome to Timesheet Management</h1>
<form method="POST">
{% csrf_token %}

<input type="date" name="start_date"/>
<input type="date" name="end_date"/>
<input type="text" name="Doctor_id">
<input type="submit" value="Search"/>

{% if error_message %}
   <div class="alert alert-danger mt-4" role="alert">
     {{error_message}}
   </div>
{% endif %}
<div>
{% if reportdata %}
<table class="table table-bordered mt-4" border="2">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Location</th>
      <th scope="col">Sector</th>
      <th scope="col">Work_date</th>
      <th scope="col">Time_in</th>
      <th scope="col">Time_out</th>
      <th scope="col">Hours_worked</th>
      <th scope="col">Hours_code</th>
      <th scope="col">Payroll</th>
      <th scope="col">Total Payroll</th>
    </tr>
  </thead>
  <tbody>

  {% for d in reportdata %}
    <tr>
      <td>{{d.doctor}}</td>
      <td>{{d.location}}</td>
      <td>{{d.sector}}</td>
      <td>{{d.work_date}}</td>
      <td>{{d.time_in}}</td>
      <td>{{d.time_out}}</td>
      <td>{{d.hours_worked}}</td>
      <td>{{d.hours_code}}</td>
      <td>{{d.payroll}}</td>
      <td>{{d.total_payroll}}</td>
    </tr>
  {% endfor %}
  {% endif %}
  </tbody>
</table>
</div>
</form>
</div>

{% endblock %}