timesheetmanagement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from workdaymanagement import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.GenerateReport,name='home'),
    path('workday/',include('workdaymanagement.urls',namespace='Workday')),
    path('user/',include('usermanagement.urls',namespace='Users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

usermanagement/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from usermanagement import views

app_name = 'Users'
urlpatterns=[
    re_path('^userslist$',views.UsersList.as_view(),name='userslist'),
    re_path('^new$',views.ProfileCreate.as_view(),name='new'),
    re_path('^(?P<pk>[0-9]+)/update$',views.ProfileUpdate.as_view(),name='profileupdate'),
    re_path('^(?P<pk>[0-9]+)/delete$',views.ProfileDelete.as_view(),name='profiledelete'),
    re_path('^login$',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    re_path('^logout$',auth_views.LogoutView.as_view(template_name='users/logged_out.html'),name='logout'),
    re_path('^signup$',views.signup,name='signup'),
    re_path('^(?P<pk>[0-9]+)$',views.ProfileDetail.as_view(),name='profiledetail'),
]

workdaymanagement/urls.py
from django.urls import path, re_path
from workdaymanagement import views
from workdaymanagement.views import WorkdayDelete,WorkdayUpdate

app_name='Workday'
urlpatterns=[
   re_path('^workdaylist$',views.GetList.as_view(),name='workday_list'),
   re_path('^new$',views.WorkdayCreate.as_view(),name="new_workday"),
   re_path('^(?P<pk>[0-9]+)/update$',views.WorkdayUpdate.as_view(),name="workday_edit"),
   re_path('^(?P<pk>[0-9]+)/delete$',WorkdayDelete.as_view(),name="workday_delete"),
   re_path('^report$',views.GenerateReport),
   re_path('^(?P<pk>[0-9]+)$', views.UserDetail.as_view(), name="workday_detail"),
]

templates/users/logged_out.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<dir>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-primary" type="submit" value="submit">Login</button>
  <a class="btn btn-primary" href="{% url 'Users:signup' %}">Signup</a>
</form>
</dir>

{% endblock %}

templates/users/profile_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid mt-4">
<form method="post">{% csrf_token %}
   <p>Are you sure you want to delete "{{ object.user.username }}"?</p>
   <input type="submit" value="Confirm">
   <a href="{{ view.get_success_url }}" class="btn btn-default">Cancel</a>
</form>
</div>>
{% endblock %}

templates/users/profile_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid mt-4">

<img src="{{object.image.url}}" height="200px" width="200px"><br>
 {{object.user.username}}<br>
 {{object.address}}<br>
 {{object.phone}}<br>
 {{object.user.email}}<br>
 {% if object.user.id != request.user.id %}
 <a href="" data-bs-toggle="popover" title="You are not authorized">Add Workday</a>
 {% else %}
 <a href="{% url 'Workday:new_workday' %}">Add Workday</a>
 {% endif %}
 <table class="table table-bordered mt-4" border="2">
  <thead>
    <tr>
      <th scope="col">Location</th>
      <th scope="col">Sector</th>
      <th scope="col">Work_date</th>
      <th scope="col">Time_in</th>
      <th scope="col">Time_out</th>
      <th scope="col">Hours_worked</th>
      <th scope="col">Hours_code</th>
      <th scope="col">Payroll</th>
      <th scope="col">Total_Payroll</th>
    </tr>
  </thead>
  <tbody>

  {% for wd in workdays_list %}
    <tr>
      <td>{{wd.location}}</td>
      <td>{{wd.sector}}</td>
      <td>{{wd.work_date}}</td>
      <td>{{wd.time_in}}</td>
      <td>{{wd.time_out}}</td>
      <td>{{wd.hours_worked}}</td>
      <td>{{wd.hours_code}}</td>
      <td>{{wd.payroll}}</td>
      <td>{{wd.total_payroll}}</td>
      <td><a href="{% url 'Workday:workday_edit' wd.id %}">Edit</a>
      <a href="{% url 'Workday:workday_delete' wd.id %}">Delete</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

templates/users/profile_update.html
{% extends 'base.html' %}

{% block content %}
<dir>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="save">Save</button>
    <a href="{{ view.get_success_url }}" class="btn btn-default">Cancel</a>
</form>
</dir>>
{% endblock %}

templates/users/profiles_new.html
{% extends 'base.html' %}

{% block content %}
<dir>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="save">Save</button>
</form>
</dir>
{% endblock %}

templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
</body>
</html>

templates/users/users_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid mt-4">
{% for u in object_list %}
<div class="mb-3" style="max-width: 900px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{u.image.url}}" height="280px" width="280px">
    </div>
    <div class="col-md-8">
      <div class="">
        <h5 ><a href="{% url 'Users:profiledetail' u.id %}">{{u.user.username}}</a></h5>
        {{u.address}}<br>
        {{u.phone}}
        <p class="card-text"><small class="text-muted">{{u.user.email}}</small></p>
           <a href="{% url 'Users:profileupdate' u.id %}">Edit</a>
           <a href="{% url 'Users:profiledelete' u.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endfor %}
</div>

{% endblock %}